<x-layouts.app title="Branch Manager Dashboard" heading="Branch Manager Dashboard">
    <div class="mb-6">
        <p class="text-slate-600">Welcome back, <strong>{{ $manager->name }}</strong>.</p>
    </div>

    <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <x-stat-tile label="Commission Cap" :value="$manager->commission_percentage" suffix="%"
            icon="tag" color="brand" hint="Your maximum share" />
        <x-stat-tile label="Commission Partners" :value="$partnerCount" icon="users" color="indigo"
            :href="route('branch.commission-partners.index')" cta="Manage partners" />
        <x-stat-tile label="Activations" :value="$stats['activations']" icon="sparkles" color="violet"
            :href="route('branch.revenue.index')" cta="View revenue" />
        <x-stat-tile label="Total Earned" :value="$stats['earned']" money icon="rupee" color="emerald"
            :href="route('branch.revenue.index')" cta="See breakdown" />
    </div>

    <x-revenue-flow
        :vip="$revenue['vip']" :product="$revenue['product']" :total="$revenue['total']"
        :product-pending="$revenue['product_pending']"
        :vip-href="route('branch.revenue.index')" :product-href="route('wallet.index')"
        vip-hint="Your share of VIP-plan activations"
        product-hint="Commission on product sales" />

    <div class="grid lg:grid-cols-2 gap-4 mb-6">
        <div class="bg-white rounded-xl shadow-sm p-5 border border-slate-100">
            <h2 class="font-semibold text-slate-800 mb-1">Your Revenue</h2>
            <p class="text-xs text-slate-400 mb-3">Your commission earnings per month, last 6 months</p>
            <x-apex-chart id="chart-branch-revenue" type="area" :height="300"
                :series="[['name' => 'Earnings', 'data' => $revenueChart['data']]]"
                :categories="$revenueChart['categories']" :currency="true" />
        </div>
        <div class="bg-white rounded-xl shadow-sm p-5 border border-slate-100">
            <h2 class="font-semibold text-slate-800 mb-1">Earnings by Partner</h2>
            <p class="text-xs text-slate-400 mb-3">Your share generated by each Commission Partner</p>
            <x-apex-chart id="chart-branch-partners" type="bar" :height="300"
                :series="[['name' => 'Your Earnings', 'data' => $partnerChart['data']]]"
                :categories="$partnerChart['categories']" :colors="['#2c704c']" :currency="true" />
        </div>
    </div>

    <div class="bg-white rounded-xl shadow-sm p-5 border border-slate-100">
        <h2 class="font-semibold mb-3">Your Branches (Cities)</h2>
        @forelse ($manager->branchCities as $city)
            <div class="flex items-center justify-between border-t border-slate-100 py-2 first:border-t-0">
                <span>{{ $city->name }}, {{ $city->state }}</span>
            </div>
        @empty
            <p class="text-slate-400 text-sm">No cities assigned yet. Contact your Super Admin.</p>
        @endforelse
    </div>
</x-layouts.app>
